CREATE TABLE bookings (
	"act_date           " DATE NOT NULL, 
	source VARCHAR(2) NOT NULL, 
	pos_ctry VARCHAR(2) NOT NULL, 
	pos_iata VARCHAR(32) NOT NULL, 
	"pos_oid  " VARCHAR(32) NOT NULL, 
	"rloc          " VARCHAR(32) NOT NULL, 
	"cre_date           " DATE NOT NULL, 
	duration INTEGER NOT NULL, 
	distance INTEGER NOT NULL, 
	dep_port VARCHAR(3) NOT NULL, 
	dep_city VARCHAR(3) NOT NULL, 
	dep_ctry VARCHAR(2) NOT NULL, 
	arr_port VARCHAR(3) NOT NULL, 
	arr_city VARCHAR(3) NOT NULL, 
	arr_ctry VARCHAR(2) NOT NULL, 
	lst_port VARCHAR(3) NOT NULL, 
	lst_city VARCHAR(3) NOT NULL, 
	lst_ctry VARCHAR(2) NOT NULL, 
	brd_port VARCHAR(3) NOT NULL, 
	brd_city VARCHAR(3) NOT NULL, 
	brd_ctry VARCHAR(2) NOT NULL, 
	off_port VARCHAR(3) NOT NULL, 
	off_city VARCHAR(3) NOT NULL, 
	off_ctry VARCHAR(2) NOT NULL, 
	mkt_port VARCHAR(6) NOT NULL, 
	mkt_city VARCHAR(6) NOT NULL, 
	mkt_ctry VARCHAR(4) NOT NULL, 
	intl INTEGER NOT NULL, 
	"route          " VARCHAR(15) NOT NULL, 
	carrier VARCHAR(2) NOT NULL, 
	bkg_class VARCHAR(1) NOT NULL, 
	cab_class VARCHAR(1) NOT NULL, 
	"brd_time           " TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	"off_time           " TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	pax INTEGER NOT NULL, 
	year INTEGER NOT NULL, 
	month INTEGER NOT NULL, 
	"oid      " VARCHAR(9)
);
